import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>NewsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
      
        <div className="container">
            <h1>About Us</h1>
             <p>This is an NewsFeed Application.<br/>
                You can see news by NewsAgency,catagory,Date</p>
        </div>
        
      
    </div>
  )
}
